[cpu]
core               = dynamic_x86
cputype            = pentium_iii
cycles             = max
[render]
aspect             = true
aspect_ratio       = -1:-1
[sdl]
mouse_wheel_key    = 0
priority           = highest,highest
